name: Deploy to VPS

on:
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: SCP .bashrc
        uses: ./.github/actions/scp
        with:
          source: ".bashrc"
          target: "/root"

      - name: SCP homepage/
        uses: ./.github/actions/scp
        with:
          source: "homepage/"
          target: "/var/www"

      - name: Symbolic link homepage/app.css -> app.css
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.VPS_SSH_KEY }}
          script: |
            ln -s /var/www/homepage/app.css /var/www/app.css/ \
            || echo "Symbolic link already exists. Skipping..."

      - name: SCP nginx.conf
        uses: ./.github/actions/scp
        with:
          source: "nginx/nginx.conf"
          target: "/etc/nginx"
          strip_components: 1

      - name: SCP gregpaidis
        uses: ./.github/actions/scp
        with:
          source: "nginx/gregpaidis"
          target: "/etc/nginx/sites-available"
          strip_components: 1

      - name: Symbolic link sites-available -> sites-enabled
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.VPS_SSH_KEY }}
          script: |
            ln -s /etc/nginx/sites-available/gregpaidis /etc/nginx/sites-enabled/ \
            || echo "Symbolic link already exists. Skipping..."

      - name: Restart NGINX
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.VPS_SSH_KEY }}
          script: |
            nginx -t && systemctl restart nginx
